[package]
name = "vivo-lockscreen-packing"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
fs_extra = "1.3.0"
rand = "0.9.1"
tempfile = "3.20.0"
walkdir = "2.5.0"
which = "8.0.0"
